// Default CALMER catalog - images from client-provided CALMER brand assets
module.exports = [
  { name: 'Zkittlez Premium Flower', description: 'Premium indoor indica flower, hand selected for quality. Deep relaxation.', category: 'Flower', price: 45, thcContent: '24% THC', cbdContent: '1% CBD', imageUrl: '/assets/products/zkittlez.jpg', stock: 50, featured: true, isNewArrival: true },
  { name: 'Gelato Hybrid Flower', description: 'Top-shelf hybrid buds. Balanced euphoria and calm.', category: 'Flower', price: 45, thcContent: '22% THC', cbdContent: '1% CBD', imageUrl: '/assets/products/gelato.jpg', stock: 45, featured: true, isNewArrival: false },
  { name: 'CBD Oil 1000mg Full Spectrum', description: 'Pure, potent, perfectly balanced full-spectrum CBD oil for anxiety relief.', category: 'Oils', price: 85, thcContent: '<0.3% THC', cbdContent: '1000mg CBD', imageUrl: '/assets/products/cbd-oil-1000.jpg', stock: 60, featured: true, isNewArrival: false },
  { name: 'CBD Oil 2000mg Full Spectrum', description: 'Extra-strength full-spectrum CBD oil for maximum wellness support.', category: 'Oils', price: 120, thcContent: '<0.3% THC', cbdContent: '2000mg CBD', imageUrl: '/assets/products/cbd-oil-2000.jpg', stock: 40, featured: false, isNewArrival: true },
  { name: 'Fruit Gummies 250mg', description: 'Deliciously dosed assorted flavors. 10 pieces, 25mg each. Consistent. Discreet.', category: 'Edibles', price: 30, thcContent: '250mg THC', cbdContent: '', imageUrl: '/assets/products/gummies.jpg', stock: 80, featured: true, isNewArrival: false },
  { name: 'Artisan Dark Chocolate Bar 500mg', description: 'Gourmet dark chocolate infused with premium THC. Elevated experiences.', category: 'Edibles', price: 40, thcContent: '500mg THC', cbdContent: '', imageUrl: '/assets/products/chocolate.jpg', stock: 55, featured: false, isNewArrival: true },
  { name: 'Live Resin Hybrid 1g', description: 'Pure. Potent. Powerful. Fresh-frozen live resin concentrate.', category: 'Concentrates', price: 55, thcContent: '78% THC', cbdContent: '', imageUrl: '/assets/products/live-resin.jpg', stock: 35, featured: false, isNewArrival: false },
  { name: 'THC Diamonds Indica 1g', description: 'Crystalline THCA diamonds for the ultimate premium experience.', category: 'Concentrates', price: 65, thcContent: '95% THC', cbdContent: '', imageUrl: '/assets/products/diamonds.jpg', stock: 25, featured: false, isNewArrival: true }
];
